CREATE TABLE SYSTEM.SEQUENCES (
		ID VARCHAR2(50) NOT NULL,
		VALUE NUMBER NOT NULL
	)
	LOGGING;

CREATE UNIQUE INDEX SYSTEM.PK_SEQUENCES ON SYSTEM.SEQUENCES (ID ASC)
	LOGGING;

ALTER TABLE SYSTEM.SEQUENCES ADD CONSTRAINT PK_SEQUENCES PRIMARY KEY (ID);

