CREATE TABLE VTB_ADMIN.SEQUENCES (
		ID VARCHAR2(50) NOT NULL,
		VALUE NUMBER(38 , 0) NOT NULL
	)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_SEQUENCES ON VTB_ADMIN.SEQUENCES (ID ASC)
	LOGGING;

ALTER TABLE VTB_ADMIN.SEQUENCES ADD CONSTRAINT PK_SEQUENCES PRIMARY KEY (ID);

