CREATE TABLE VTB_ADMIN.USERS (
		ID_USER NVARCHAR2(256),
		MAIL_USER NVARCHAR2(128),
		IP_USER NVARCHAR2(128)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.VAR_SELECT_VALUES_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_SELECT NUMBER,
		ID_VAR NUMBER,
		SELECT_VALUE NVARCHAR2(1023)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.ORGANIZATIONS (
		IDCONTRACTOR NUMBER(38 , 0) NOT NULL,
		IDORGANIZATIONCRM CHAR(12),
		ORGANIZATIONNAME VARCHAR2(128),
		FULLORGANIZATIONNAME VARCHAR2(1024),
		WORKPHONE VARCHAR2(20),
		FAX VARCHAR2(20),
		RAITING VARCHAR2(20),
		EMAIL VARCHAR2(64),
		EMPLOYEESCOUNT NUMBER(38 , 0),
		DATEOFREGISTRATION DATE,
		CLIENTCATEGORY VARCHAR2(32),
		SECTOR VARCHAR2(128),
		BUSINESSDESCRIPTION VARCHAR2(2048),
		CITY VARCHAR2(128),
		REGION VARCHAR2(128),
		LEGALADDRESS VARCHAR2(256),
		REALADDRESS VARCHAR2(256),
		POSTALCODE VARCHAR2(20),
		INN VARCHAR2(20),
		KPP VARCHAR2(20),
		ID_OKOPF NUMBER(38 , 0)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.TARGET_TYPE (
		ID_TARGET_TYPE NUMBER(38 , 0) NOT NULL,
		NAME_TARGET_TYPE VARCHAR2(256)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.RATING_TYPE (
		ID_RATING_TYPE NUMBER(38 , 0) NOT NULL,
		NAME_RATING_TYPE VARCHAR2(128)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.ATTRIBUTES (
		ID NUMBER NOT NULL,
		ID_VAR NUMBER,
		ID_PROCESS NUMBER,
		ARRAY_IDX NUMBER,
		VALUE_VAR NVARCHAR2(256),
		VALUE_INT NUMBER,
		VALUE_FLOAT FLOAT(126)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.STAGES_IN_ROLE (
		ID_ROLE NUMBER NOT NULL,
		ID_STAGE NUMBER NOT NULL
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.TYPE_PROCESS_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_TYPE_PROCESS NUMBER,
		DESCRIPTION_PROCESS NVARCHAR2(256),
		LIMIT_DAY NUMBER,
		SCHEMA_VAR BLOB,
		ID_GROUP NUMBER,
		SCHEMA_IMAGE BLOB
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.VAR_NODES (
		ID_NODES NUMBER NOT NULL,
		ID_VAR_ROOT NUMBER,
		ID_VAR_NODE NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.STAGES_IN_ROLE_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_ROLE NUMBER,
		ID_STAGE NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.OPERATOR (
		ID_OPERATOR NUMBER(38 , 0) NOT NULL,
		LOGIN VARCHAR2(32) NOT NULL,
		RE NUMBER(38 , 0) NOT NULL,
		RA NUMBER(38 , 0) NOT NULL,
		FA VARCHAR2(40),
		IM VARCHAR2(40),
		OT VARCHAR2(40),
		ID_DEPARTMENT NUMBER(38 , 0)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.TYPE_PROCESS (
		ID_TYPE_PROCESS NUMBER NOT NULL,
		DESCRIPTION_PROCESS NVARCHAR2(256),
		LIMIT_DAY NUMBER,
		SCHEMA_VAR BLOB,
		ID_GROUP NUMBER,
		SCHEMA_IMAGE BLOB
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.VAR_NODES_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_NODES NUMBER,
		ID_VAR_ROOT NUMBER,
		ID_VAR_NODE NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.ATTACHMENTS (
		ID_ATTACH NUMBER NOT NULL,
		ID_DOC NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.USER_IN_ROLE_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_ROLE NUMBER,
		ID_USER NVARCHAR2(256)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.MQSCHEDULERSHEET (
		ID NUMBER(38 , 0) NOT NULL,
		START_TIME DATE,
		END_TIME DATE,
		DAYS_OF_WEEK NUMBER(38 , 0),
		STATUS NUMBER(38 , 0),
		ID_DEPARTMENT NUMBER(38 , 0) NOT NULL
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.LIMIT_TYPE (
		ID_LIMIT_TYPE NUMBER(38 , 0) NOT NULL,
		NAME_LIMIT_TYPE VARCHAR2(128)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.PATTERN_INTEREST_RATE (
		ID_PATTERN_INTEREST_RATE NUMBER(38 , 0) NOT NULL,
		NAME_PATTERN_INTEREST_RATE VARCHAR2(256)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.TASKS (
		ID_TASK NUMBER NOT NULL,
		ID_TYPE_PROCESS NUMBER,
		ID_PROCESS NUMBER,
		ID_STAGE_TO NUMBER,
		ID_STAGE_FROM NUMBER,
		TYPE_TRANSACTION NUMBER,
		DATEOFCOMING TIMESTAMP(6),
		DATEOFTAKING TIMESTAMP(6),
		DATEOFCOMPLATION TIMESTAMP(6),
		ID_USER NVARCHAR2(256),
		TYPE_COMPLATION NUMBER,
		SIGNATURE_T BLOB,
		SIGNATURE_C BLOB
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.PROCESS_PARAMETERS (
		ID_TYPE_PROCESS NUMBER NOT NULL,
		TYPE_PARAMETER NVARCHAR2(32) NOT NULL,
		VALUE_VAR NVARCHAR2(2000)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.EDGE_MERGES (
		ID_EDGE NUMBER,
		ID_STAGE NUMBER,
		TYPE_MERGE NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.REPORT_STAGES_STAT_GTT (
		O_ID_STAGE NUMBER(38 , 0),
		O_NUMB_ACTIVE NUMBER(38 , 0),
		O_NUMB_ENTER NUMBER(38 , 0),
		O_NUMB_LEAVE NUMBER(38 , 0),
		O_NUMB_GOBACK NUMBER(38 , 0),
		O_NUMB_EXPIRED NUMBER(38 , 0),
		O_MAX NUMBER(38 , 0),
		O_MIN NUMBER(38 , 0),
		O_MIDDLEDATE NUMBER(15 , 2),
		O_DISPERSIA NUMBER(15 , 2),
		O_ALL FLOAT(126)
	)
	NOLOGGING;

CREATE TABLE VTB_ADMIN.VAR_TYPES (
		ID_VAR_TYPE NUMBER NOT NULL,
		NAME_TYPE NVARCHAR2(255)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.MESSAGES_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_MESSAGE NUMBER,
		DATE_MESSAGE TIMESTAMP(6),
		MESSAGE_TEXT NVARCHAR2(2000),
		ID_ATTACH NUMBER,
		ID_PROCESS_FROM NUMBER,
		ID_ROLE_FROM NUMBER,
		ID_STAGE_FROM NUMBER,
		ID_USER_FROM NVARCHAR2(256),
		ID_TYPE_PROCESS_TO NUMBER,
		ID_PROCESS_TO NUMBER,
		ID_ROLE_TO NUMBER,
		ID_STAGE_TO NUMBER,
		ID_USER_TO NVARCHAR2(256)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.OWNERSHIP_FORM_TYPE (
		ID_OWNERSHIP_FORM_TYPE NUMBER(38 , 0) NOT NULL,
		NAME_OWNERSHIP_FORM_TYPE VARCHAR2(512)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.CONTRACTOR_TYPE (
		ID_CONTRACTOR_TYPE NUMBER(38 , 0) NOT NULL,
		NAME_CONTRACTOR_TYPE VARCHAR2(128)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.LINK_OWNFORM_DOCTYPE (
		ID_OWNERSHIP_FORM_TYPE NUMBER(38 , 0) NOT NULL,
		ID_DOCUMENT_TYPE NUMBER(38 , 0) NOT NULL
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.STATUS_PROCESSES (
		ID_STATUS NUMBER NOT NULL,
		DESCRIPTION_STATUS NVARCHAR2(32)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.GROUPS_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID NUMBER,
		NAME_GROUP NVARCHAR2(128)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.EDGE_VARS (
		ID_EDGE NUMBER,
		ID_VAR NUMBER,
		ALIAS_VAR NVARCHAR2(2000)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.SCHEDULERS (
		ID_SCHEDULER NUMBER NOT NULL,
		DATE_EXECUTE TIMESTAMP(6),
		NAME_TASK NVARCHAR2(128),
		PARAMETERS NVARCHAR2(256),
		CLASS_ACTION NVARCHAR2(256),
		STATUS_EXECUTE NVARCHAR2(10),
		MESSAGE_EXECUTE NVARCHAR2(256)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.DOCUMENTS_TYPE (
		ID_DOCUMENT_TYPE NUMBER(38 , 0) NOT NULL,
		NAME_DOCUMENT_TYPE VARCHAR2(512)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.ATTRIBUTES_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID NUMBER,
		ID_VAR NUMBER,
		ID_PROCESS NUMBER,
		ARRAY_IDX NUMBER,
		VALUE_VAR NVARCHAR2(256),
		VALUE_INT NUMBER,
		VALUE_FLOAT FLOAT(126)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.MANAGERS (
		ID_MANAGER NUMBER(38 , 0) NOT NULL,
		FIO VARCHAR2(128) NOT NULL,
		REASON VARCHAR2(128),
		POSITION VARCHAR2(128),
		ID_CONTRACTOR NUMBER(38 , 0) NOT NULL
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.SUB_PROCESSES (
		ID_PAR_TYPE_PROCESS NUMBER NOT NULL,
		ID_CH_TYPE_PROCESS NUMBER NOT NULL
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.REPORT_HISTORY_PROCESS_GTT (
		O_DATE TIMESTAMP(6),
		O_ID_STAGE FLOAT(126),
		O_DESCRIPTION VARCHAR2(4000)
	)
	NOLOGGING;

CREATE TABLE VTB_ADMIN.VARIABLES_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_VAR NUMBER,
		NAME_VAR NVARCHAR2(128),
		DESCRIPTION NVARCHAR2(1023),
		ID_VAR_TYPE NUMBER,
		ADDITION_VAR NVARCHAR2(2000),
		ID_TYPE_PROCESS NUMBER,
		VALUE_BY_DEFAULT NVARCHAR2(256),
		IS_ID NUMBER,
		IS_MAIN NUMBER,
		ACTIVE NUMBER,
		ORDER_VAR NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.ROLES_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_ROLE NUMBER,
		NAME_ROLE NVARCHAR2(128),
		ID_TYPE_PROCESS NUMBER,
		ACTIVE NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.HOLDINGS (
		ID_CONTRACTOR NUMBER(38 , 0) NOT NULL,
		ID_HOLDING_CRM CHAR(12),
		NAME_HOLDING VARCHAR2(256)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.COMMISSION_TYPE (
		ID_COMMISSION_TYPE NUMBER(38 , 0) NOT NULL,
		NAME_COMMISSION_TYPE VARCHAR2(256)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.PUNITIVE_MEASURE (
		ID_MEASURE NUMBER(38 , 0) NOT NULL,
		NAME_MEASURE VARCHAR2(1024)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.ROLES_PERMISSIONS_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_ROLE NUMBER,
		ID_VAR NUMBER,
		ID_PERMISSION NUMBER,
		ORDER_VAR NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.STAGES (
		ID_STAGE NUMBER NOT NULL,
		DESCRIPTION_STAGE NVARCHAR2(256),
		LIMIT_DAY NUMBER,
		TYPE_LIMIT_DAY NUMBER,
		ATTENTION_DAY NUMBER,
		ACTION_CLASS_ON_ENTRY BLOB,
		ACTION_CLASS_ON_EXIT BLOB,
		ID_TYPE_PROCESS NUMBER,
		ACTIVE NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.VAR_SELECT_VALUES (
		ID_SELECT NUMBER NOT NULL,
		ID_VAR NUMBER,
		SELECT_VALUE NVARCHAR2(1023)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.TMP (
		TYPE_TRANSACTION NUMBER(38 , 0),
		DATEOFTAKING TIMESTAMP(6),
		DATEOFCOMPLATION TIMESTAMP(6),
		ID_USER NVARCHAR2(256)
	)
	NOLOGGING;

CREATE TABLE VTB_ADMIN.DATA_SOURCES_PAR (
		ID_DS NUMBER NOT NULL,
		NAME_PAR NVARCHAR2(128) NOT NULL,
		VALUE_PAR NVARCHAR2(256)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.STAGES_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_STAGE NUMBER,
		DESCRIPTION_STAGE NVARCHAR2(256),
		LIMIT_DAY NUMBER,
		TYPE_LIMIT_DAY NUMBER,
		ATTENTION_DAY NUMBER,
		ACTION_CLASS_ON_ENTRY BLOB,
		ACTION_CLASS_ON_EXIT BLOB,
		ID_TYPE_PROCESS NUMBER,
		ACTIVE NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.PROCESSES_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_PROCESS NUMBER,
		DATEOFCOMMING TIMESTAMP(6),
		DATEOFCOMPLETION TIMESTAMP(6),
		ID_STATUS NUMBER,
		ID_TYPE_PROCESS NUMBER,
		ID_PAR_PROCESS NUMBER DEFAULT NULL
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.MESSAGES (
		ID_MESSAGE NUMBER NOT NULL,
		DATE_MESSAGE TIMESTAMP(6),
		MESSAGE_TEXT NVARCHAR2(2000),
		ID_ATTACH NUMBER,
		ID_PROCESS_FROM NUMBER,
		ID_ROLE_FROM NUMBER,
		ID_STAGE_FROM NUMBER,
		ID_USER_FROM NVARCHAR2(256),
		ID_TYPE_PROCESS_TO NUMBER,
		ID_PROCESS_TO NUMBER,
		ID_ROLE_TO NUMBER,
		ID_STAGE_TO NUMBER,
		ID_USER_TO NVARCHAR2(256)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.DATA_SOURCES (
		ID_DS NUMBER NOT NULL,
		ID_TYPE_PROCESS NUMBER,
		NAME_DS NVARCHAR2(128),
		TYPE_DS NVARCHAR2(128)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.SP_MAP_VARIABLES (
		ID_PAR_VARIABLE NUMBER NOT NULL,
		ID_CH_VARIABLE NUMBER NOT NULL,
		IN_OR_OUT NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.SPO_SETTINGS (
		ID_DEPARTMENT NUMBER(38 , 0) NOT NULL,
		DEPARTMENT_NAME VARCHAR2(256),
		FILEHOST_IP VARCHAR2(256) NOT NULL,
		FILEHOST_TYPE NUMBER(38 , 0) DEFAULT 0 NOT NULL,
		MQ_HOSTNAME VARCHAR2(64),
		MQ_PORT VARCHAR2(16),
		MQ_QUEUEMANAGER VARCHAR2(64),
		MQ_SERVERCHANNEL VARCHAR2(64),
		MQ_QUEUENAME VARCHAR2(64)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.ORGANIZATIONS_DEPENDENCY (
		ID_DEPENDENCY NUMBER(38 , 0) NOT NULL,
		ID_CONTRACTOR_1 NUMBER(38 , 0) NOT NULL,
		ID_CONTRACTOR_2 NUMBER(38 , 0) NOT NULL,
		RELATION_TYPE NUMBER(38 , 0)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.OPPORTUNITY_TYPE (
		ID_OPPORTUNITY_TYPE NUMBER(38 , 0) NOT NULL,
		NAME_OPPORTUNITY_TYPE VARCHAR2(256)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.SEQUENCES (
		ID VARCHAR2(50) NOT NULL,
		VALUE NUMBER(38 , 0) NOT NULL
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.REGIONS (
		ID_REGION NUMBER(38 , 0) NOT NULL,
		NAME_REGION VARCHAR2(20),
		REGION_RATING VARCHAR2(20)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.FILE_REQUEST (
		ID_REQUEST NUMBER(38 , 0) NOT NULL,
		PRIORITY NUMBER(38 , 0) NOT NULL,
		STATUS NUMBER(38 , 0) NOT NULL,
		UNID VARCHAR2(64) NOT NULL,
		ID_DEP_REQUESTED NUMBER(38 , 0) NOT NULL
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.INDUSTRY (
		ID_INDUSTRY NUMBER(38 , 0) NOT NULL,
		NAME_INDUSTRY VARCHAR2(20),
		INDUSTRY_RATING VARCHAR2(20)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.PATTERN_PAID_PERCENT_TYPE (
		ID_PAID_PERCENT_TYPE NUMBER(38 , 0) NOT NULL,
		NAME_PAID_PERCENT_TYPE VARCHAR2(128)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.ROLES_PERMISSIONS (
		ID_ROLE NUMBER NOT NULL,
		ID_VAR NUMBER NOT NULL,
		ID_PERMISSION NUMBER NOT NULL,
		ORDER_VAR NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.TASKS_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_TASK NUMBER,
		ID_TYPE_PROCESS NUMBER,
		ID_PROCESS NUMBER,
		ID_STAGE_TO NUMBER,
		ID_STAGE_FROM NUMBER,
		TYPE_TRANSACTION NUMBER,
		DATEOFCOMING TIMESTAMP(6),
		DATEOFTAKING TIMESTAMP(6),
		DATEOFCOMPLATION TIMESTAMP(6),
		ID_USER NVARCHAR2(256),
		TYPE_COMPLATION NUMBER,
		SIGNATURE_T BLOB,
		SIGNATURE_C BLOB
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.USERS_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_USER NVARCHAR2(256),
		MAIL_USER NVARCHAR2(128),
		IP_USER NVARCHAR2(128)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.MESSAGE (
		IDMESSAGE NUMBER(38 , 0) NOT NULL,
		MFROM VARCHAR2(64) NOT NULL,
		MTO VARCHAR2(64) NOT NULL,
		MSUBJECT VARCHAR2(256),
		MESSAGE VARCHAR2(2048),
		MTIMESTAMP TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
		ISREAD NUMBER(38 , 0) DEFAULT 0 NOT NULL,
		MFROMFULL VARCHAR2(256) NOT NULL,
		MTOFULL VARCHAR2(256) NOT NULL
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.USER_IN_ROLE (
		ID_ROLE NUMBER NOT NULL,
		ID_USER NVARCHAR2(256) NOT NULL
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.VAR_CONNECTIONS (
		ID_CONNECTION NUMBER NOT NULL,
		ID_VAR_PARENT NUMBER,
		ID_VAR_CHILD NUMBER,
		ORDER_VAR NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.ROLES (
		ID_ROLE NUMBER NOT NULL,
		NAME_ROLE NVARCHAR2(128),
		ID_TYPE_PROCESS NUMBER,
		ACTIVE NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.STAGES_PERMISSIONS_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_STAGE NUMBER,
		ID_VAR NUMBER,
		ID_PERMISSION NUMBER,
		ORDER_VAR NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.CONTRACTORS (
		ID_CONTRACTOR NUMBER(38 , 0) NOT NULL,
		TYPE NUMBER(38 , 0)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.PROCESSES (
		ID_PROCESS NUMBER NOT NULL,
		DATEOFCOMMING TIMESTAMP(6),
		DATEOFCOMPLETION TIMESTAMP(6),
		ID_STATUS NUMBER,
		ID_TYPE_PROCESS NUMBER,
		ID_PAR_PROCESS NUMBER DEFAULT NULL
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.VARIABLES (
		ID_VAR NUMBER NOT NULL,
		NAME_VAR NVARCHAR2(128),
		DESCRIPTION NVARCHAR2(1023),
		ID_VAR_TYPE NUMBER,
		ADDITION_VAR NVARCHAR2(2000),
		ID_TYPE_PROCESS NUMBER,
		VALUE_BY_DEFAULT NVARCHAR2(256),
		IS_ID NUMBER,
		IS_MAIN NUMBER,
		ACTIVE NUMBER,
		ORDER_VAR NUMBER,
		ID_DS NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.SHAREHOLDERS (
		ID_SHAREHOLDER NUMBER(38 , 0) NOT NULL,
		FIO VARCHAR2(128) NOT NULL,
		CATEGORY VARCHAR2(128),
		PART VARCHAR2(128),
		ID_CONTRACTOR NUMBER(38 , 0) NOT NULL
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.STAGES_PERMISSIONS (
		ID_STAGE NUMBER NOT NULL,
		ID_VAR NUMBER NOT NULL,
		ID_PERMISSION NUMBER NOT NULL,
		ORDER_VAR NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.VAR_CONNECTIONS_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_CONNECTION NUMBER,
		ID_VAR_PARENT NUMBER,
		ID_VAR_CHILD NUMBER,
		ORDER_VAR NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.PROCESS_PARAMETERS_HISTORY (
		ID_ACTION NUMBER NOT NULL,
		ID_TRANSACTION NUMBER,
		TYPE_SQL NUMBER,
		ID_TYPE_PROCESS NUMBER,
		TYPE_PARAMETER NVARCHAR2(32),
		VALUE_VAR NVARCHAR2(2000)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.APPFILES (
		UNID VARCHAR2(128) NOT NULL,
		FILENAME VARCHAR2(256),
		FILEDATA BLOB,
		FILETYPE VARCHAR2(256),
		ID_OWNER NUMBER,
		OWNER_TYPE NUMBER,
		WHO_ADD NUMBER,
		DATE_OF_ADDITION DATE,
		DATE_OF_EXPIRATION DATE,
		ISACCEPTED NUMBER,
		WHOACCEPTED NUMBER,
		DATE_OF_ACCEPT DATE,
		SIGNATURE BLOB,
		ID_APPL NUMBER,
		ID_GROUP NUMBER
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.TRANSACTION (
		ID_TRANSACTION NUMBER NOT NULL,
		DATE_TRANSACTION TIMESTAMP(6),
		ID_USER NVARCHAR2(256),
		IP_ADDRESS NVARCHAR2(15),
		NAME_ACTION NVARCHAR2(256)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.GROUPS (
		ID_GROUP NUMBER NOT NULL,
		NAME_GROUP NVARCHAR2(128)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.BASE_RATE (
		CODE NUMBER(38 , 0) NOT NULL,
		RATE_NAME VARCHAR2(128),
		RATE_DESCRIPTION VARCHAR2(2048)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.AUTHORIZED_BODY (
		ID_BODY NUMBER(38 , 0) NOT NULL,
		NAME_BODY VARCHAR2(256)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.DEPARTMENTS (
		ID_DEPARTMENT NUMBER(38 , 0) NOT NULL,
		SHORTNAME VARCHAR2(256),
		FULLNAME VARCHAR2(1024)
	)
	LOGGING;

CREATE TABLE VTB_ADMIN.SP_MAP_ROLES (
		ID_PAR_ROLE NUMBER NOT NULL,
		ID_CH_ROLE NUMBER NOT NULL
	)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.VAR_SELECT_VALUES_HISTORY_PK ON VTB_ADMIN.VAR_SELECT_VALUES_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_ORGANIZATIONS ON VTB_ADMIN.ORGANIZATIONS (IDCONTRACTOR ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_TARGET_TYPE ON VTB_ADMIN.TARGET_TYPE (ID_TARGET_TYPE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_RATING_TYPE ON VTB_ADMIN.RATING_TYPE (ID_RATING_TYPE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_ATTRIBUTES ON VTB_ADMIN.ATTRIBUTES (ID ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_STAGES_IN_ROLE ON VTB_ADMIN.STAGES_IN_ROLE (ID_ROLE ASC, ID_STAGE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_TYPE_PROCESS_HISTORY ON VTB_ADMIN.TYPE_PROCESS_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_VAR_NODES ON VTB_ADMIN.VAR_NODES (ID_NODES ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_STAGES_IN_ROLE_HISTORY ON VTB_ADMIN.STAGES_IN_ROLE_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.OPERATOR_PK ON VTB_ADMIN.OPERATOR (ID_OPERATOR ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_TYPE_PROCESS ON VTB_ADMIN.TYPE_PROCESS (ID_TYPE_PROCESS ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_VAR_NODES_HISTORY ON VTB_ADMIN.VAR_NODES_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_ATTACHMENTS ON VTB_ADMIN.ATTACHMENTS (ID_ATTACH ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_USER_IN_ROLE_HISTORY ON VTB_ADMIN.USER_IN_ROLE_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_MQSCHEDULERSHEET ON VTB_ADMIN.MQSCHEDULERSHEET (ID ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_LIMIT_TYPE ON VTB_ADMIN.LIMIT_TYPE (ID_LIMIT_TYPE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_PATTERN_INTEREST_RATE ON VTB_ADMIN.PATTERN_INTEREST_RATE (ID_PATTERN_INTEREST_RATE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_TASKS ON VTB_ADMIN.TASKS (ID_TASK ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_PROCESS_PARAMETERS ON VTB_ADMIN.PROCESS_PARAMETERS (ID_TYPE_PROCESS ASC, TYPE_PARAMETER ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_VAR_TYPES ON VTB_ADMIN.VAR_TYPES (ID_VAR_TYPE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_MESSAGES_HISTORY ON VTB_ADMIN.MESSAGES_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_OWNERSHIP_FORM_TYPE ON VTB_ADMIN.OWNERSHIP_FORM_TYPE (ID_OWNERSHIP_FORM_TYPE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_CONTRACTOR_TYPE ON VTB_ADMIN.CONTRACTOR_TYPE (ID_CONTRACTOR_TYPE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_LINK_OWNFORM_DOCTYPE ON VTB_ADMIN.LINK_OWNFORM_DOCTYPE (ID_DOCUMENT_TYPE ASC, ID_OWNERSHIP_FORM_TYPE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_STATUS_PROCESSES ON VTB_ADMIN.STATUS_PROCESSES (ID_STATUS ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_GROUPS_HISTORY ON VTB_ADMIN.GROUPS_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_SCHEDULERS ON VTB_ADMIN.SCHEDULERS (ID_SCHEDULER ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_DOCUMENT_TYPE ON VTB_ADMIN.DOCUMENTS_TYPE (ID_DOCUMENT_TYPE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_ATTRIBUTES_HISTORY ON VTB_ADMIN.ATTRIBUTES_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_MANAGERS ON VTB_ADMIN.MANAGERS (ID_MANAGER ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_SUB_PROCESSES ON VTB_ADMIN.SUB_PROCESSES (ID_PAR_TYPE_PROCESS ASC, ID_CH_TYPE_PROCESS ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_VARIABLES_HISTORY ON VTB_ADMIN.VARIABLES_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_ROLES_HISTORY ON VTB_ADMIN.ROLES_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_HOLDINGS ON VTB_ADMIN.HOLDINGS (ID_CONTRACTOR ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_COMMISSION_TYPE ON VTB_ADMIN.COMMISSION_TYPE (ID_COMMISSION_TYPE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_PUNITIVE_MEASURE ON VTB_ADMIN.PUNITIVE_MEASURE (ID_MEASURE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_ROLES_PERMISSIONS_HISTORY ON VTB_ADMIN.ROLES_PERMISSIONS_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_STAGES ON VTB_ADMIN.STAGES (ID_STAGE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_VAR_SELECT_VALUES ON VTB_ADMIN.VAR_SELECT_VALUES (ID_SELECT ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_DATA_SOURCES_PAR ON VTB_ADMIN.DATA_SOURCES_PAR (ID_DS ASC, NAME_PAR ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_STAGES_HISTORY ON VTB_ADMIN.STAGES_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_PROCESSES_HISTORY ON VTB_ADMIN.PROCESSES_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_MESSAGES ON VTB_ADMIN.MESSAGES (ID_MESSAGE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_DATA_SOURCES ON VTB_ADMIN.DATA_SOURCES (ID_DS ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_SP_MAP_VARIABLES ON VTB_ADMIN.SP_MAP_VARIABLES (ID_PAR_VARIABLE ASC, ID_CH_VARIABLE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_SPO_SETTINGS ON VTB_ADMIN.SPO_SETTINGS (ID_DEPARTMENT ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_ORGANIZATIONS_DEPENDENCY ON VTB_ADMIN.ORGANIZATIONS_DEPENDENCY (ID_DEPENDENCY ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_OPPORTUNITY_TYPE ON VTB_ADMIN.OPPORTUNITY_TYPE (ID_OPPORTUNITY_TYPE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_SEQUENCES ON VTB_ADMIN.SEQUENCES (ID ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.XPK–≈√»ŒÕ€ ON VTB_ADMIN.REGIONS (ID_REGION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_FILE_REQUEST ON VTB_ADMIN.FILE_REQUEST (ID_REQUEST ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_INDUSTRY ON VTB_ADMIN.INDUSTRY (ID_INDUSTRY ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_PATTERN_PAID_PERCENT_TYPE ON VTB_ADMIN.PATTERN_PAID_PERCENT_TYPE (ID_PAID_PERCENT_TYPE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_ROLES_PERMISSIONS ON VTB_ADMIN.ROLES_PERMISSIONS (ID_ROLE ASC, ID_VAR ASC, ID_PERMISSION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_TASKS_HISTORY ON VTB_ADMIN.TASKS_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_USERS_HISTORY ON VTB_ADMIN.USERS_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.XPK_MESSAGE ON VTB_ADMIN.MESSAGE (IDMESSAGE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_USER_IN_ROLE ON VTB_ADMIN.USER_IN_ROLE (ID_ROLE ASC, ID_USER ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_VAR_CONNECTIONS ON VTB_ADMIN.VAR_CONNECTIONS (ID_CONNECTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_ROLES ON VTB_ADMIN.ROLES (ID_ROLE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_STAGES_PERMISSIONS_HISTORY ON VTB_ADMIN.STAGES_PERMISSIONS_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_CONTRACTORS ON VTB_ADMIN.CONTRACTORS (ID_CONTRACTOR ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_PROCESSES ON VTB_ADMIN.PROCESSES (ID_PROCESS ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_VARIABLES ON VTB_ADMIN.VARIABLES (ID_VAR ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_SHAREHOLDERS ON VTB_ADMIN.SHAREHOLDERS (ID_SHAREHOLDER ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_STAGES_PERMISSIONS ON VTB_ADMIN.STAGES_PERMISSIONS (ID_STAGE ASC, ID_VAR ASC, ID_PERMISSION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_VAR_CONNECTIONS_HISTORY ON VTB_ADMIN.VAR_CONNECTIONS_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_PROCESS_PARAMETERS_HISTORY ON VTB_ADMIN.PROCESS_PARAMETERS_HISTORY (ID_ACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_APPFILES ON VTB_ADMIN.APPFILES (UNID ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_TRANSACTION ON VTB_ADMIN.TRANSACTION (ID_TRANSACTION ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_GROUPS ON VTB_ADMIN.GROUPS (ID_GROUP ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_BASE_RATE ON VTB_ADMIN.BASE_RATE (CODE ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_AUTHORIZED_BODY ON VTB_ADMIN.AUTHORIZED_BODY (ID_BODY ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_DEPARTMENTS ON VTB_ADMIN.DEPARTMENTS (ID_DEPARTMENT ASC)
	LOGGING;

CREATE UNIQUE INDEX VTB_ADMIN.PK_SP_MAP_ROLES ON VTB_ADMIN.SP_MAP_ROLES (ID_PAR_ROLE ASC, ID_CH_ROLE ASC)
	LOGGING;

ALTER TABLE VTB_ADMIN.VAR_SELECT_VALUES_HISTORY ADD CONSTRAINT VAR_SELECT_VALUES_HISTORY_PK PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.ORGANIZATIONS ADD CONSTRAINT PK_ORGANIZATIONS PRIMARY KEY (IDCONTRACTOR);

ALTER TABLE VTB_ADMIN.TARGET_TYPE ADD CONSTRAINT PK_TARGET_TYPE PRIMARY KEY (ID_TARGET_TYPE);

ALTER TABLE VTB_ADMIN.RATING_TYPE ADD CONSTRAINT PK_RATING_TYPE PRIMARY KEY (ID_RATING_TYPE);

ALTER TABLE VTB_ADMIN.ATTRIBUTES ADD CONSTRAINT PK_ATTRIBUTES PRIMARY KEY (ID);

ALTER TABLE VTB_ADMIN.STAGES_IN_ROLE ADD CONSTRAINT PK_STAGES_IN_ROLE PRIMARY KEY (ID_ROLE, ID_STAGE);

ALTER TABLE VTB_ADMIN.TYPE_PROCESS_HISTORY ADD CONSTRAINT PK_TYPE_PROCESS_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.VAR_NODES ADD CONSTRAINT PK_VAR_NODES PRIMARY KEY (ID_NODES);

ALTER TABLE VTB_ADMIN.STAGES_IN_ROLE_HISTORY ADD CONSTRAINT PK_STAGES_IN_ROLE_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.OPERATOR ADD CONSTRAINT OPERATOR_PK PRIMARY KEY (ID_OPERATOR);

ALTER TABLE VTB_ADMIN.TYPE_PROCESS ADD CONSTRAINT PK_TYPE_PROCESS PRIMARY KEY (ID_TYPE_PROCESS);

ALTER TABLE VTB_ADMIN.VAR_NODES_HISTORY ADD CONSTRAINT PK_VAR_NODES_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.ATTACHMENTS ADD CONSTRAINT PK_ATTACHMENTS PRIMARY KEY (ID_ATTACH);

ALTER TABLE VTB_ADMIN.USER_IN_ROLE_HISTORY ADD CONSTRAINT PK_USER_IN_ROLE_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.MQSCHEDULERSHEET ADD CONSTRAINT PK_MQSCHEDULERSHEET PRIMARY KEY (ID);

ALTER TABLE VTB_ADMIN.LIMIT_TYPE ADD CONSTRAINT PK_LIMIT_TYPE PRIMARY KEY (ID_LIMIT_TYPE);

ALTER TABLE VTB_ADMIN.PATTERN_INTEREST_RATE ADD CONSTRAINT PK_PATTERN_INTEREST_RATE PRIMARY KEY (ID_PATTERN_INTEREST_RATE);

ALTER TABLE VTB_ADMIN.TASKS ADD CONSTRAINT PK_TASKS PRIMARY KEY (ID_TASK);

ALTER TABLE VTB_ADMIN.PROCESS_PARAMETERS ADD CONSTRAINT PK_PROCESS_PARAMETERS PRIMARY KEY (ID_TYPE_PROCESS, TYPE_PARAMETER);

ALTER TABLE VTB_ADMIN.VAR_TYPES ADD CONSTRAINT PK_VAR_TYPES PRIMARY KEY (ID_VAR_TYPE);

ALTER TABLE VTB_ADMIN.MESSAGES_HISTORY ADD CONSTRAINT PK_MESSAGES_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.OWNERSHIP_FORM_TYPE ADD CONSTRAINT PK_OWNERSHIP_FORM_TYPE PRIMARY KEY (ID_OWNERSHIP_FORM_TYPE);

ALTER TABLE VTB_ADMIN.CONTRACTOR_TYPE ADD CONSTRAINT PK_CONTRACTOR_TYPE PRIMARY KEY (ID_CONTRACTOR_TYPE);

ALTER TABLE VTB_ADMIN.LINK_OWNFORM_DOCTYPE ADD CONSTRAINT PK_LINK_OWNFORM_DOCTYPE PRIMARY KEY (ID_DOCUMENT_TYPE, ID_OWNERSHIP_FORM_TYPE);

ALTER TABLE VTB_ADMIN.STATUS_PROCESSES ADD CONSTRAINT PK_STATUS_PROCESSES PRIMARY KEY (ID_STATUS);

ALTER TABLE VTB_ADMIN.GROUPS_HISTORY ADD CONSTRAINT PK_GROUPS_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.SCHEDULERS ADD CONSTRAINT PK_SCHEDULERS PRIMARY KEY (ID_SCHEDULER);

ALTER TABLE VTB_ADMIN.DOCUMENTS_TYPE ADD CONSTRAINT PK_DOCUMENT_TYPE PRIMARY KEY (ID_DOCUMENT_TYPE);

ALTER TABLE VTB_ADMIN.ATTRIBUTES_HISTORY ADD CONSTRAINT PK_ATTRIBUTES_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.MANAGERS ADD CONSTRAINT PK_MANAGERS PRIMARY KEY (ID_MANAGER);

ALTER TABLE VTB_ADMIN.SUB_PROCESSES ADD CONSTRAINT PK_SUB_PROCESSES PRIMARY KEY (ID_PAR_TYPE_PROCESS, ID_CH_TYPE_PROCESS);

ALTER TABLE VTB_ADMIN.VARIABLES_HISTORY ADD CONSTRAINT PK_VARIABLES_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.ROLES_HISTORY ADD CONSTRAINT PK_ROLES_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.HOLDINGS ADD CONSTRAINT PK_HOLDINGS PRIMARY KEY (ID_CONTRACTOR);

ALTER TABLE VTB_ADMIN.COMMISSION_TYPE ADD CONSTRAINT PK_COMMISSION_TYPE PRIMARY KEY (ID_COMMISSION_TYPE);

ALTER TABLE VTB_ADMIN.PUNITIVE_MEASURE ADD CONSTRAINT PK_PUNITIVE_MEASURE PRIMARY KEY (ID_MEASURE);

ALTER TABLE VTB_ADMIN.ROLES_PERMISSIONS_HISTORY ADD CONSTRAINT PK_ROLES_PERMISSIONS_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.STAGES ADD CONSTRAINT PK_STAGES PRIMARY KEY (ID_STAGE);

ALTER TABLE VTB_ADMIN.VAR_SELECT_VALUES ADD CONSTRAINT PK_VAR_SELECT_VALUES PRIMARY KEY (ID_SELECT);

ALTER TABLE VTB_ADMIN.DATA_SOURCES_PAR ADD CONSTRAINT PK_DATA_SOURCES_PAR PRIMARY KEY (ID_DS, NAME_PAR);

ALTER TABLE VTB_ADMIN.STAGES_HISTORY ADD CONSTRAINT PK_STAGES_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.PROCESSES_HISTORY ADD CONSTRAINT PK_PROCESSES_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.MESSAGES ADD CONSTRAINT PK_MESSAGES PRIMARY KEY (ID_MESSAGE);

ALTER TABLE VTB_ADMIN.DATA_SOURCES ADD CONSTRAINT PK_DATA_SOURCES PRIMARY KEY (ID_DS);

ALTER TABLE VTB_ADMIN.SP_MAP_VARIABLES ADD CONSTRAINT PK_SP_MAP_VARIABLES PRIMARY KEY (ID_PAR_VARIABLE, ID_CH_VARIABLE);

ALTER TABLE VTB_ADMIN.SPO_SETTINGS ADD CONSTRAINT PK_SPO_SETTINGS PRIMARY KEY (ID_DEPARTMENT);

ALTER TABLE VTB_ADMIN.ORGANIZATIONS_DEPENDENCY ADD CONSTRAINT PK_ORGANIZATIONS_DEPENDENCY PRIMARY KEY (ID_DEPENDENCY);

ALTER TABLE VTB_ADMIN.OPPORTUNITY_TYPE ADD CONSTRAINT PK_OPPORTUNITY_TYPE PRIMARY KEY (ID_OPPORTUNITY_TYPE);

ALTER TABLE VTB_ADMIN.SEQUENCES ADD CONSTRAINT PK_SEQUENCES PRIMARY KEY (ID);

ALTER TABLE VTB_ADMIN.REGIONS ADD CONSTRAINT XPK–≈√»ŒÕ€ PRIMARY KEY (ID_REGION);

ALTER TABLE VTB_ADMIN.FILE_REQUEST ADD CONSTRAINT PK_FILE_REQUEST PRIMARY KEY (ID_REQUEST);

ALTER TABLE VTB_ADMIN.INDUSTRY ADD CONSTRAINT PK_INDUSTRY PRIMARY KEY (ID_INDUSTRY);

ALTER TABLE VTB_ADMIN.PATTERN_PAID_PERCENT_TYPE ADD CONSTRAINT PK_PATTERN_PAID_PERCENT_TYPE PRIMARY KEY (ID_PAID_PERCENT_TYPE);

ALTER TABLE VTB_ADMIN.ROLES_PERMISSIONS ADD CONSTRAINT PK_ROLES_PERMISSIONS PRIMARY KEY (ID_ROLE, ID_VAR, ID_PERMISSION);

ALTER TABLE VTB_ADMIN.TASKS_HISTORY ADD CONSTRAINT PK_TASKS_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.USERS_HISTORY ADD CONSTRAINT PK_USERS_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.MESSAGE ADD CONSTRAINT XPK_MESSAGE PRIMARY KEY (IDMESSAGE);

ALTER TABLE VTB_ADMIN.USER_IN_ROLE ADD CONSTRAINT PK_USER_IN_ROLE PRIMARY KEY (ID_ROLE, ID_USER);

ALTER TABLE VTB_ADMIN.VAR_CONNECTIONS ADD CONSTRAINT PK_VAR_CONNECTIONS PRIMARY KEY (ID_CONNECTION);

ALTER TABLE VTB_ADMIN.ROLES ADD CONSTRAINT PK_ROLES PRIMARY KEY (ID_ROLE);

ALTER TABLE VTB_ADMIN.STAGES_PERMISSIONS_HISTORY ADD CONSTRAINT PK_STAGES_PERMISSIONS_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.CONTRACTORS ADD CONSTRAINT PK_CONTRACTORS PRIMARY KEY (ID_CONTRACTOR);

ALTER TABLE VTB_ADMIN.PROCESSES ADD CONSTRAINT PK_PROCESSES PRIMARY KEY (ID_PROCESS);

ALTER TABLE VTB_ADMIN.VARIABLES ADD CONSTRAINT PK_VARIABLES PRIMARY KEY (ID_VAR);

ALTER TABLE VTB_ADMIN.SHAREHOLDERS ADD CONSTRAINT PK_SHAREHOLDERS PRIMARY KEY (ID_SHAREHOLDER);

ALTER TABLE VTB_ADMIN.STAGES_PERMISSIONS ADD CONSTRAINT PK_STAGES_PERMISSIONS PRIMARY KEY (ID_STAGE, ID_VAR, ID_PERMISSION);

ALTER TABLE VTB_ADMIN.VAR_CONNECTIONS_HISTORY ADD CONSTRAINT PK_VAR_CONNECTIONS_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.PROCESS_PARAMETERS_HISTORY ADD CONSTRAINT PK_PROCESS_PARAMETERS_HISTORY PRIMARY KEY (ID_ACTION);

ALTER TABLE VTB_ADMIN.APPFILES ADD CONSTRAINT PK_APPFILES PRIMARY KEY (UNID);

ALTER TABLE VTB_ADMIN.TRANSACTION ADD CONSTRAINT PK_TRANSACTION PRIMARY KEY (ID_TRANSACTION);

ALTER TABLE VTB_ADMIN.GROUPS ADD CONSTRAINT PK_GROUPS PRIMARY KEY (ID_GROUP);

ALTER TABLE VTB_ADMIN.BASE_RATE ADD CONSTRAINT PK_BASE_RATE PRIMARY KEY (CODE);

ALTER TABLE VTB_ADMIN.AUTHORIZED_BODY ADD CONSTRAINT PK_AUTHORIZED_BODY PRIMARY KEY (ID_BODY);

ALTER TABLE VTB_ADMIN.DEPARTMENTS ADD CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (ID_DEPARTMENT);

ALTER TABLE VTB_ADMIN.SP_MAP_ROLES ADD CONSTRAINT PK_SP_MAP_ROLES PRIMARY KEY (ID_PAR_ROLE, ID_CH_ROLE);

CREATE TRIGGER VTB_ADMIN.VAR_SELECT_VALUES_H_INSERT 
	BEFORE INSERT ON VTB_ADMIN.VAR_SELECT_VALUES_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  select var_select_values_history_seq.NEXTVAL into :NEW.id_action from dual;
END;

CREATE TRIGGER VTB_ADMIN.ATTRIBUTES_INSERT 
	BEFORE INSERT ON VTB_ADMIN.ATTRIBUTES
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT attributes_seq.NEXTVAL INTO :NEW.id FROM dual;
  --:NEW.value_int := to_number( :NEW.VALUE_VAR );
  --:NEW.value_float := to_number( :NEW.VALUE_VAR );
END;

CREATE TRIGGER VTB_ADMIN.TYPE_PROCESS_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.TYPE_PROCESS_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT type_process_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.VAR_NODES_INSERT 
	BEFORE INSERT ON VTB_ADMIN.VAR_NODES
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT var_nodes_seq.NEXTVAL INTO :NEW.id_nodes FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.STAGES_IN_ROLE_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.STAGES_IN_ROLE_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT stages_in_role_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.TYPE_PROCESS_INSERT 
	BEFORE INSERT ON VTB_ADMIN.TYPE_PROCESS
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT type_process_seq.NEXTVAL INTO :NEW.id_type_process FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.VAR_NODES_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.VAR_NODES_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT var_nodes_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.ATTACHMENTS_INSERT 
	BEFORE INSERT ON VTB_ADMIN.ATTACHMENTS
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT attach_seq.NEXTVAL INTO :NEW.id_attach FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.USER_IN_ROLE_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.USER_IN_ROLE_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT user_in_role_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.TASKS_INSERT 
	BEFORE INSERT ON VTB_ADMIN.TASKS
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT tasks_seq.NEXTVAL INTO :NEW.id_task FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.PROCESS_PARAMETERS_INSERT 
	BEFORE INSERT ON VTB_ADMIN.PROCESS_PARAMETERS
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT process_parameters_seq.NEXTVAL INTO :NEW.id_type_process FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.VAR_TYPES_INSERT 
	BEFORE INSERT ON VTB_ADMIN.VAR_TYPES
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT var_types_seq.NEXTVAL INTO :NEW.id_VAR_type FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.MESSAGES_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.MESSAGES_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT messages_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.GROUPS_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.GROUPS_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT groups_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.SCHEDULERS_INSERT 
	BEFORE INSERT ON VTB_ADMIN.SCHEDULERS
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT schedulers_seq.NEXTVAL INTO :NEW.id_scheduler FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.ATTRIBUTES_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.ATTRIBUTES_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT attributes_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.VARIABLES_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.VARIABLES_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT variables_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.ROLES_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.ROLES_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT roles_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.ROLES_PERMISSS_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.ROLES_PERMISSIONS_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT roles_permissions_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.STAGES_INSERT 
	BEFORE INSERT ON VTB_ADMIN.STAGES
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT stages_seq.NEXTVAL INTO :NEW.id_stage FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.VAR_SELECT_VALUES_INSERT 
	BEFORE INSERT ON VTB_ADMIN.VAR_SELECT_VALUES
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  select var_select_values_seq.NEXTVAL into :NEW.id_select from dual;
END;

CREATE TRIGGER VTB_ADMIN.STAGES_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.STAGES_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT stages_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.PROCESSES_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.PROCESSES_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT processes_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.MESSAGES_INSERT 
	BEFORE INSERT ON VTB_ADMIN.MESSAGES
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT messages_seq.NEXTVAL INTO :NEW.id_message FROM dual;
  :NEW.date_message := current_date;
END;

CREATE TRIGGER VTB_ADMIN.DATA_SOURCES_INSERT 
	BEFORE INSERT ON VTB_ADMIN.DATA_SOURCES
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT data_sources_seq.NEXTVAL INTO :NEW.id_ds FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.ON_BEFORE_INSERT_REQUEST 
	BEFORE INSERT ON VTB_ADMIN.FILE_REQUEST
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
Begin
  if (:new.id_request is null) then
     select seq_id_request.nextval into :new.id_request from dual;
  end if;
  select 0,0 into :new.status, :new.priority from dual;
end;

CREATE TRIGGER VTB_ADMIN.TASKS_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.TASKS_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT tasks_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.USERS_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.USERS_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT users_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.ON_BEFORE_INSERT_MESSAGE 
	BEFORE INSERT ON VTB_ADMIN.MESSAGE
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  --if (:new.idMessage is null) then
      select seq_id_message.nextval into :new.idMessage from dual;
      select CURRENT_TIMESTAMP, 0 into :new.mTimeStamp, :new.isRead from dual;
  --end if;
END;

CREATE TRIGGER VTB_ADMIN.VAR_CONNECTIONS_INSERT 
	BEFORE INSERT ON VTB_ADMIN.VAR_CONNECTIONS
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT VAR_CONNECTIONS_seq.NEXTVAL INTO :NEW.id_connection FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.ROLES_INSERT 
	BEFORE INSERT ON VTB_ADMIN.ROLES
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT roles_seq.NEXTVAL INTO :NEW.id_role FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.STAGES_PERMISSS_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.STAGES_PERMISSIONS_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
 SELECT stages_permissions_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.PROCESSES_INSERT 
	BEFORE INSERT ON VTB_ADMIN.PROCESSES
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
DECLARE
  id_par_process_exists NUMBER;
BEGIN
  
  if not ( :new.id_par_process is null ) then
    begin
      select count(id_process) 
        into id_par_process_exists
        from processes p
        where p.id_process = :new.id_par_process;
        if ( id_par_process_exists = 0 ) then
          raise no_data_found;
        end if;
    exception 
      when no_data_found then
      raise_application_error ( -20000,  'No such parent process' );
      return;
    end;
  end if;
  
  SELECT PROCESSES_seq.NEXTVAL INTO :NEW.id_process FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.VARIABLES_INSERT 
	BEFORE INSERT ON VTB_ADMIN.VARIABLES
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT variables_seq.NEXTVAL INTO :NEW.id_var FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.VAR_CONNECTIONS_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.VAR_CONNECTIONS_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT var_connections_history_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.PROCESS_PARAMS_HISTORY_INSERT 
	BEFORE INSERT ON VTB_ADMIN.PROCESS_PARAMETERS_HISTORY
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT PROCESS_PARAMETERS_HISTORY_seq.NEXTVAL INTO :NEW.id_action FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.TRANSACTION_INSERT 
	BEFORE INSERT ON VTB_ADMIN.TRANSACTION
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT transaction_seq.NEXTVAL INTO :NEW.id_transaction FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.GROUPS_INSERT 
	BEFORE INSERT ON VTB_ADMIN.GROUPS
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
  SELECT groups_seq.NEXTVAL INTO :NEW.id_group FROM dual;
END;

CREATE TRIGGER VTB_ADMIN.ON_BEFORE_INSERT_DEPARTMENT 
	BEFORE INSERT ON VTB_ADMIN.DEPARTMENTS
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
Begin
  if (:new.id_department is null) then
     select seq_id_department.nextval into :new.id_department from dual;
  end if;

end;

